### ISSUE TITLE
Check before you start - results page

### ISSUE THREAD

**Issue by owenm6** [UKHomeOffice/home-office-design-system#31]
Results page which forms part of the 'Check before you start' pattern. Helps ensure users are inputting correct qualifying data before progressing to the actual service.

![check-before-you-start-results](https://user-images.githubusercontent.com/13904084/30317636-949d3dea-97a2-11e7-8723-a5868c63c5ad.png)

**Comment by christaylor-hod** [comment]
Possibly needs a write up and contributing to the GDS attern

**Comment by karypun** [comment]
Documented in GOV.UK design patterns in dropbox.
